/* eslint-disable @typescript-eslint/no-redundant-type-constituents -- generated by Supabase */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: '12.2.12 (cd3cf9e)'
  }
  public: {
    Tables: {
      categories: {
        Row: {
          color: string | null
          created_at: string | null
          icon: string | null
          id: string
          name: string
          updated_at: string | null
        }
        Insert: {
          color?: string | null
          created_at?: string | null
          icon?: string | null
          id?: string
          name: string
          updated_at?: string | null
        }
        Update: {
          color?: string | null
          created_at?: string | null
          icon?: string | null
          id?: string
          name?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      expenses: {
        Row: {
          amount: number
          category_id: string
          created_at: string | null
          currency: string
          expense_date: string
          id: string
          name: string
          original_amount: number | null
          original_currency: string | null
          plan_id: string
          plan_item_id: string | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          amount: number
          category_id: string
          created_at?: string | null
          currency: string
          expense_date?: string
          id?: string
          name: string
          original_amount?: number | null
          original_currency?: string | null
          plan_id: string
          plan_item_id?: string | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          amount?: number
          category_id?: string
          created_at?: string | null
          currency?: string
          expense_date?: string
          id?: string
          name?: string
          original_amount?: number | null
          original_currency?: string | null
          plan_id?: string
          plan_item_id?: string | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'expenses_category_id_fkey'
            columns: ['category_id']
            isOneToOne: false
            referencedRelation: 'categories'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'expenses_plan_id_fkey'
            columns: ['plan_id']
            isOneToOne: false
            referencedRelation: 'plans'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'expenses_plan_item_context_fkey'
            columns: ['plan_item_id', 'plan_id', 'category_id']
            isOneToOne: false
            referencedRelation: 'plan_items'
            referencedColumns: ['id', 'plan_id', 'category_id']
          },
          {
            foreignKeyName: 'expenses_plan_item_id_fkey'
            columns: ['plan_item_id']
            isOneToOne: false
            referencedRelation: 'plan_items'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'expenses_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
        ]
      }
      notification_outbox: {
        Row: {
          actor_user_id: string
          attempts: number
          available_at: string
          claimed_at: string | null
          created_at: string
          entity_id: string
          entity_type: string
          event_type: string
          id: string
          last_error: string | null
          payload: Json
          processed_at: string | null
          recipient_ids: string[] | null
          status: string
          updated_at: string
        }
        Insert: {
          actor_user_id: string
          attempts?: number
          available_at?: string
          claimed_at?: string | null
          created_at?: string
          entity_id: string
          entity_type: string
          event_type: string
          id?: string
          last_error?: string | null
          payload?: Json
          processed_at?: string | null
          recipient_ids?: string[] | null
          status?: string
          updated_at?: string
        }
        Update: {
          actor_user_id?: string
          attempts?: number
          available_at?: string
          claimed_at?: string | null
          created_at?: string
          entity_id?: string
          entity_type?: string
          event_type?: string
          id?: string
          last_error?: string | null
          payload?: Json
          processed_at?: string | null
          recipient_ids?: string[] | null
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'notification_outbox_actor_user_id_fkey'
            columns: ['actor_user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
        ]
      }
      notifications: {
        Row: {
          actor_user_id: string | null
          body: string
          created_at: string
          deleted_at: string | null
          entity_id: string
          entity_type: string
          id: string
          payload: Json
          push_attempted_at: string | null
          push_error: string | null
          push_sent_at: string | null
          read_at: string | null
          title: string
          type: string
          user_id: string
        }
        Insert: {
          actor_user_id?: string | null
          body: string
          created_at?: string
          deleted_at?: string | null
          entity_id: string
          entity_type: string
          id?: string
          payload?: Json
          push_attempted_at?: string | null
          push_error?: string | null
          push_sent_at?: string | null
          read_at?: string | null
          title: string
          type: string
          user_id: string
        }
        Update: {
          actor_user_id?: string | null
          body?: string
          created_at?: string
          deleted_at?: string | null
          entity_id?: string
          entity_type?: string
          id?: string
          payload?: Json
          push_attempted_at?: string | null
          push_error?: string | null
          push_sent_at?: string | null
          read_at?: string | null
          title?: string
          type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'notifications_actor_user_id_fkey'
            columns: ['actor_user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'notifications_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
        ]
      }
      plan_items: {
        Row: {
          amount: number
          category_id: string
          created_at: string | null
          id: string
          is_completed: boolean | null
          is_fixed_payment: boolean
          name: string
          plan_id: string
          updated_at: string | null
        }
        Insert: {
          amount: number
          category_id: string
          created_at?: string | null
          id?: string
          is_completed?: boolean | null
          is_fixed_payment?: boolean
          name: string
          plan_id: string
          updated_at?: string | null
        }
        Update: {
          amount?: number
          category_id?: string
          created_at?: string | null
          id?: string
          is_completed?: boolean | null
          is_fixed_payment?: boolean
          name?: string
          plan_id?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'plan_items_category_id_fkey'
            columns: ['category_id']
            isOneToOne: false
            referencedRelation: 'categories'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'plan_items_plan_id_fkey'
            columns: ['plan_id']
            isOneToOne: false
            referencedRelation: 'plans'
            referencedColumns: ['id']
          },
        ]
      }
      plan_shares: {
        Row: {
          created_at: string | null
          id: string
          permission_level: string
          plan_id: string
          shared_by_user_id: string
          shared_with_user_id: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          permission_level: string
          plan_id: string
          shared_by_user_id: string
          shared_with_user_id: string
        }
        Update: {
          created_at?: string | null
          id?: string
          permission_level?: string
          plan_id?: string
          shared_by_user_id?: string
          shared_with_user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'plan_shares_plan_id_fkey'
            columns: ['plan_id']
            isOneToOne: false
            referencedRelation: 'plans'
            referencedColumns: ['id']
          },
        ]
      }
      plans: {
        Row: {
          created_at: string | null
          currency: string
          end_date: string
          id: string
          name: string
          owner_id: string
          start_date: string
          status: string
          template_id: string
          total: number
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          currency?: string
          end_date: string
          id?: string
          name: string
          owner_id: string
          start_date: string
          status: string
          template_id: string
          total?: number
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          currency?: string
          end_date?: string
          id?: string
          name?: string
          owner_id?: string
          start_date?: string
          status?: string
          template_id?: string
          total?: number
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'plans_template_id_fkey'
            columns: ['template_id']
            isOneToOne: false
            referencedRelation: 'templates'
            referencedColumns: ['id']
          },
        ]
      }
      push_subscriptions: {
        Row: {
          auth: string
          created_at: string
          endpoint: string
          id: string
          p256dh: string
          revoked_at: string | null
          updated_at: string
          user_agent: string | null
          user_id: string
        }
        Insert: {
          auth: string
          created_at?: string
          endpoint: string
          id?: string
          p256dh: string
          revoked_at?: string | null
          updated_at?: string
          user_agent?: string | null
          user_id: string
        }
        Update: {
          auth?: string
          created_at?: string
          endpoint?: string
          id?: string
          p256dh?: string
          revoked_at?: string | null
          updated_at?: string
          user_agent?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'push_subscriptions_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
        ]
      }
      template_items: {
        Row: {
          amount: number
          category_id: string
          created_at: string | null
          id: string
          is_fixed_payment: boolean
          name: string
          template_id: string
          updated_at: string | null
        }
        Insert: {
          amount: number
          category_id: string
          created_at?: string | null
          id?: string
          is_fixed_payment?: boolean
          name: string
          template_id: string
          updated_at?: string | null
        }
        Update: {
          amount?: number
          category_id?: string
          created_at?: string | null
          id?: string
          is_fixed_payment?: boolean
          name?: string
          template_id?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'template_items_category_id_fkey'
            columns: ['category_id']
            isOneToOne: false
            referencedRelation: 'categories'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'template_items_template_id_fkey'
            columns: ['template_id']
            isOneToOne: false
            referencedRelation: 'templates'
            referencedColumns: ['id']
          },
        ]
      }
      template_shares: {
        Row: {
          created_at: string | null
          id: string
          permission_level: string
          shared_by_user_id: string
          shared_with_user_id: string
          template_id: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          permission_level: string
          shared_by_user_id: string
          shared_with_user_id: string
          template_id: string
        }
        Update: {
          created_at?: string | null
          id?: string
          permission_level?: string
          shared_by_user_id?: string
          shared_with_user_id?: string
          template_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'template_shares_template_id_fkey'
            columns: ['template_id']
            isOneToOne: false
            referencedRelation: 'templates'
            referencedColumns: ['id']
          },
        ]
      }
      templates: {
        Row: {
          created_at: string | null
          currency: string
          duration: string
          id: string
          name: string
          owner_id: string
          total: number
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          currency?: string
          duration: string
          id?: string
          name: string
          owner_id: string
          total?: number
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          currency?: string
          duration?: string
          id?: string
          name?: string
          owner_id?: string
          total?: number
          updated_at?: string | null
        }
        Relationships: []
      }
      users: {
        Row: {
          avatar: string | null
          created_at: string
          email: string
          id: string
          name: string
          preferences: Json | null
          updated_at: string | null
        }
        Insert: {
          avatar?: string | null
          created_at?: string
          email: string
          id: string
          name: string
          preferences?: Json | null
          updated_at?: string | null
        }
        Update: {
          avatar?: string | null
          created_at?: string
          email?: string
          id?: string
          name?: string
          preferences?: Json | null
          updated_at?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      calculate_plan_status: {
        Args: {
          p_current_status?: string
          p_end_date: string
          p_start_date: string
        }
        Returns: string
      }
      create_expense_transaction: {
        Args: { p_complete_plan_item?: boolean; p_expense: Json }
        Returns: Json
      }
      create_expenses_transaction: {
        Args: { p_complete_plan_items?: boolean; p_expenses: Json }
        Returns: Json
      }
      create_plan_with_items: {
        Args: { p_items?: Json; p_plan: Json }
        Returns: Json
      }
      create_template_with_items: {
        Args: { p_items?: Json; p_template: Json }
        Returns: Json
      }
      delete_expenses_and_reconcile: {
        Args: { p_expense_ids: string[] }
        Returns: number
      }
      delete_plan_transaction: { Args: { p_plan_id: string }; Returns: Json }
      delete_template_transaction: {
        Args: { p_template_id: string }
        Returns: Json
      }
      get_plan_expense_summary: {
        Args: { p_plan_id: string }
        Returns: {
          actual_amount: number
          category_id: string
          expense_count: number
          planned_amount: number
          remaining_amount: number
        }[]
      }
      get_plan_items_with_tracking: {
        Args: { p_plan_id: string }
        Returns: {
          amount: number
          category_id: string
          created_at: string
          expense_count: number
          id: string
          is_completed: boolean
          name: string
          plan_id: string
          remaining_amount: number
          spent_amount: number
          updated_at: string
        }[]
      }
      get_plan_items_with_tracking_by_category: {
        Args: { p_category_id: string; p_plan_id: string }
        Returns: {
          amount: number
          category_id: string
          created_at: string
          expense_count: number
          id: string
          is_completed: boolean
          name: string
          plan_id: string
          remaining_amount: number
          spent_amount: number
          updated_at: string
        }[]
      }
      get_plan_overview_snapshots: {
        Args: { p_plan_ids: string[] }
        Returns: {
          actual_amount: number
          category_color: string
          category_icon: string
          category_id: string
          category_name: string
          expense_count: number
          plan_id: string
          planned_amount: number
          remaining_amount: number
        }[]
      }
      get_plan_shared_users: {
        Args: { p_plan_id: string }
        Returns: {
          permission_level: string
          shared_at: string
          user_email: string
          user_id: string
          user_name: string
        }[]
      }
      get_recent_expenses_page: {
        Args: {
          p_category_id?: string
          p_limit?: number
          p_offset?: number
          p_search?: string
          p_sort_by?: string
          p_user_id: string
        }
        Returns: {
          amount: number
          categories: Json
          category_id: string
          created_at: string
          currency: string
          expense_date: string
          id: string
          name: string
          original_amount: number
          original_currency: string
          plan_id: string
          plan_item_id: string
          plans: Json
          updated_at: string
          user_id: string
        }[]
      }
      get_template_shared_users: {
        Args: { p_template_id: string }
        Returns: {
          permission_level: string
          shared_at: string
          user_email: string
          user_id: string
          user_name: string
        }[]
      }
      search_users_for_sharing: {
        Args: { entity_id: string; entity_type: string; q: string }
        Returns: {
          email: string
          id: string
          name: string
        }[]
      }
      update_plan_with_items: {
        Args: { p_items?: Json; p_plan: Json; p_plan_id: string }
        Returns: Json
      }
      update_template_with_items: {
        Args: { p_items?: Json; p_template: Json; p_template_id: string }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema['Enums']
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema['CompositeTypes']
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
