import lucideIconMap from 'src/config/lucide-icon-map.json'

export const LUCIDE_SPRITE_PATH = '/icons/lucide-sprite.svg'

const evaToLucide = lucideIconMap as Record<string, string>

/**
 * Maps the app's (and the database's) `eva-*` icon names onto Lucide symbols in the
 * trimmed sprite generated by `npm run icons:build`. Names without a mapping fall
 * through to the Eva webfont so user data never renders an empty icon.
 */
export function resolveIcon(name: string): { icon: string } | undefined {
  if (name.startsWith('lucide-')) {
    return { icon: `svguse:${LUCIDE_SPRITE_PATH}#${name.slice('lucide-'.length)}` }
  }

  if (!name.startsWith('eva-')) return undefined

  const base = name.slice('eva-'.length).replace(/-outline$/, '')
  const lucideName = evaToLucide[base]
  if (!lucideName) return undefined

  return { icon: `svguse:${LUCIDE_SPRITE_PATH}#${lucideName}` }
}
